### ISSUE TITLE
Melhorar descrição da interface do usuário (figma)

### ISSUE THREAD

**Issue by ipatriciahonorato** [2023M8T2-Inteli/grupo5#65]
Feedback sprint 2:

A interface de vocês está bastante fluída e simples de se utilizar. Parabéns.
A forma como ela foi descrita na documentação não condiz com a qualidade com ela foi apresentada. Melhorar a descrição da interface na documentação, adicionando mais detalhes sobre a interface.

**Comment by VZeferino** [comment]
Feito hoje de manhã em conjunto com o Leão.
